name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: 
      - main

env:
  NODE_VERSION: '22'
  OUTPUT_LOCATION: 'dist/lensdata'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: 🟢 Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 🔍 Verify environment
        run: |
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Repository contents:"
          ls -la

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔧 Build Angular application
        run: npm run build
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: 📋 Verify build output
        run: |
          echo "Build completed. Checking output directory..."
          if [ -d "${{ env.OUTPUT_LOCATION }}" ]; then
            echo "✅ Build output found in ${{ env.OUTPUT_LOCATION }}"
            echo "Contents:"
            ls -la ${{ env.OUTPUT_LOCATION }}
            echo "Total files: $(find ${{ env.OUTPUT_LOCATION }} -type f | wc -l)"
          else
            echo "❌ Build output directory not found: ${{ env.OUTPUT_LOCATION }}"
            echo "Available directories in dist/:"
            ls -la dist/ || echo "No dist directory found"
            exit 1
          fi

      - name: 🚀 Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_BEACH_0A8A87A1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # App configuration
          app_location: "/"
          api_location: ""
          output_location: ${{ env.OUTPUT_LOCATION }}
          # Build configuration
          skip_app_build: true # We build manually above for better control
          skip_api_build: true # No API in this Angular-only app

      - name: ✅ Deployment Status
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "Your Angular app has been deployed to Azure Static Web Apps"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: 🧹 Close Pull Request Preview
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_BEACH_0A8A87A1E }}
          action: "close"
          app_location: "/"

      - name: ✅ Cleanup Complete
        run: echo "🧹 Pull request preview environment cleaned up successfully"
